### ISSUE TITLE
Error in JobsController on update

### ISSUE THREAD

**Issue by mdav43** [rizafahmi/phoenix-jobs#3]
I'm getting a error when editing a job an unsure if this is to do with update deps I'm using.

*Error: field id had type string but type integer*
```
def update(conn, params) do
    IO.inspect params["type"]
    job = Repo.get(ElixirJobs.Jobs, params["id"])
    job = %{job | title: params["title"], description: params["description"],
      job_type: params["type"], job_status: params["status"]}
    Repo.update(job)
    redirect conn, Router.index_path(:index)
  end
```

Running:
```
      {:phoenix, "~> 0.7.2"},
      {:cowboy, "~> 1.0"},
      {:exrm, "~> 0.14.2" },
      {:postgrex,"~> 0.6"},
      {:ecto, "~> 0.2.3"}
```

**Comment by rizafahmi** [comment]
Well, we need to convert `params["id"]` from string to integer since `jobs.id` is integer in the database. So we should change this line `job = Repo.get(ElixirJobs.Jobs, params["id"])` into `job = Repo.get(PhoenixJobsFour.Jobs, String.to_integer(params["id"]))`
